const jokes = [
    "Why do Czechs always drink beer? Because it's the only way to wash down the cabbage.",
    "What do you call a Czech who doesn't drink beer? A disappointment.",
    'Whats the Czech word for "beer" ? "Pivo".Whats the English word for "beer" ? "Pivo".Whats the Czech word for "more beer" ? "Ještě pivo".',
    "Why are Czechs so bad at driving? Because they're always looking for the nearest bar.",
    'Whats the Czech word for "traffic jam"? "A line of cars waiting to get to the bar',
    "Why are Czechs so good at chess? Because they're always planning their next beer.",
    "Why are Czechs so good at skiing? Because they're always trying to get away from their problems.",
    'Whats the Czech word for "money"? "Beer tokens".',
    "Why are Czechs so good at gambling? Because they're always willing to risk everything for a beer.",
    'Whats the Czech word for "everything"? "My last beer".',
    'Whats the Czech word for "attention" ? "Free beer".',
    'Whats the Czech word for "friend"? "Someone who will buy me a beer".',
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "What do you call a programmer from Finland? Nerdic.",
    'Why do programmers always mix up work and pleasure? Because they "byte" into both!',
    "Why did the programmer go broke? Because he used up all his cache.",
    'Why did the developer go broke? Because he lost his domain in a bet.',
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the computer catch a cold? It had a bad Windows.",
    'Why did the programmer quit his job? Because he didnt get arrays.',
    "Why do Java developers wear glasses? Because they don't see sharp.",
    'Why dont programmers like to go outside? The sunlight causes too many reflections.',
    'Why was the JavaScript developer sad? Because he didn’t "get" callbacks.',
    'Why did the programmer go broke? Because he used up all his "cache"!',
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What do you call a fish with no eyes? Fsh.",
    'I told my wife she was drawing her eyebrows too high. She looked surprised.',
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    'Why couldn’t the bicycle stand up by itself? Because it was two-tired.',
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    'I used to play piano by ear, but now I use my hands.',
    "I used to be a baker, but I couldn't make enough dough.",
    'I used to be a baker, but I couldn’t make enough dough.',
    "I'm on a whiskey diet. I've lost three days already.",
    'I used to be a baker, but I couldn’t make enough dough.',
];